### ISSUE TITLE
The implementation of astroML.density_estimation.Events.prior does not match the paper by scargle

### ISSUE THREAD

**Issue by cs224** [astroML/astroML#105]
The matlab code for the Scargle paper can be found here: http://www.ascl.net/1209.001
Specifically the find_blocks.m file here: https://arxiv.org/src/1207.5578v3/anc/find_blocks.m

The code in find_blocks.m reads:

    ncp_prior = 4 - log( fp_rate / ( 0.0136 * num_points .^ (0.478 ) ) )

Which does not match the python implementation:

    return 4 - np.log(73.53 * self.p0 * (N ** -0.478))

The correct implementation would read:

    return 4 - np.log(73.53 * self.p0 * (Ntot ** -0.478))

**Comment by cs224** [comment]
If I read the paper correctly then also the treatment of "gamma" is not correct.
In the paper: http://iopscience.iop.org/article/10.1088/0004-637X/764/2/167/pdf
on page 5 left top it reads: ... is simply implemented in the algorithm ... because the contribution of the the prior to block fitness, ..., can be implemented by adding the constant log gamma (called ncp_prior in the MatLab code) to the fitness of each block.

So if I read this correctly then gamma is a constant for a given Ntot and not like currently implemented a function of N and Ntot.

**Comment by bsipocz** [comment]
The implementation of Bayesian blocks has been moved upstream to astropy. That version has minor updates both in code and references compared to this original in astroML, and your concerns have been addressed there.
Thus I'm going to close the issue now, please reopen a new issue in the astropy repository if you spot something else.
