### ISSUE TITLE
Knuth's Rule Implementation depends totally on Initial value (and hence on Freedman's rule)

### ISSUE THREAD

**Issue by ZacKeskin** [astroML/astroML#107]
As described in the [docs](http://www.astroml.org/modules/generated/astroML.density_estimation.knuth_bin_width.html#astroML.density_estimation.knuth_bin_width) , the optimal number of bins is given by M, where M maximises the log of the posterior: see eq(31) from https://arxiv.org/abs/physics/0605197

Therefore, the implementation in `density_estimation/histtools.py` involves using Scipy.Optimize to find the maximum log posterior, but the initial value parameter appears to make all the difference here, which suggests two bugs in the following code (lines 230-232):

    dx0, bins0 = freedman_bin_width(data, True)
    M0 = len(bins0) - 1
    M = optimize.fmin(knuthF, len(bins0), disp=disp)[0]`

1. The second parameter of `fmin` is x0 - this should be the initial value and so presumably should be `M0` (which is currently not used)
2. The optimisation returns totally different values depending on the initial x0 parameter. 

Currently, the implementation seems to use the Freedman bin width, and then only make minor tweaks. Am I missing something, or is this not satisfying the Knuth paper? Has it been confirmed that this is a convex problem suitable for scipy.optimize?

**Comment by bsipocz** [comment]
The histogram functionalies has been moved upstream to astropy. I keep this issue open though for a little more here and investigate a but, and if needed will reopen it upstream.

**Comment by bsipocz** [comment]
The histograms have been deprecated from here, thus this issue got moved upstream to https://github.com/astropy/astropy/issues/8326.
