### ISSUE TITLE
fetch_sdss_galaxy_colors not working (?)

### ISSUE THREAD

**Issue by mirca** [astroML/astroML#122]
I tried the following code
```
from astroML.datasets import fetch_sdss_galaxy_colors
data = fetch_sdss_galaxy_colors()
```
which is part of [this](http://www.astroml.org/examples/datasets/plot_sdss_galaxy_colors.html#example-datasets-plot-sdss-galaxy-colors) example, but it returned a ``urllib.error.HTTPError: HTTP Error 404: Not Found``.

I'm on Python 3 on a OSX machine and using ``astroML-0.3``.

Thanks!!

**Comment by AnimeshSinha1309** [comment]
[SDSS Galaxy Colors - Python Script](https://github.com/astroML/astroML/blob/master/astroML/datasets/sdss_galaxy_colors.py) - should query the dataset, is throwing the error. Can I please take this issue.

**Comment by bsipocz** [comment]
Thanks @AnimeshSinha1309 for the interest. I'm in the middle of integrating astroquery.sdss to be used under the hood here rather than directly querying the sdss server.

**Comment by bsipocz** [comment]
This example now works with v0.4rc1, but the astroquery migration is still TODO.
