### ISSUE TITLE
incompatible to sklearn 0.20

### ISSUE THREAD

**Issue by olebole** [astroML/astroML#123]
astroML uses the `sklean.mixture.GMM` class which was deprecated in 0.18 and removed in 0.20: https://github.com/astroML/astroML/blob/d23267b9d1df49e089ce5043c43020ad64aeead8/astroML/density_estimation/xdeconv.py#L17
That makes several [tests fail](https://ci.debian.net/data/autopkgtest/testing/amd64/a/astroml/1201576/log.gz). This is also covered by [Debian#911708](https://bugs.debian.org/911708).

**Comment by bsipocz** [comment]
Thanks @olebole, it's great to see that debian also packages astroml.
 An update the code to be compatible with new releases is in the works, and will be out very soon.

**Comment by bsipocz** [comment]
This has been fixed by #125
