### ISSUE TITLE
change data url in astroML/astroML/datasets/rrlyrae_mags.py

### ISSUE THREAD

**Issue by saint-germain** [astroML/astroML#179]
new URL is at:

http://faculty.washington.edu/ivezic/DMbook/data/RRLyrae.fit

**Comment by bsipocz** [comment]
Thank you @saint-germain for reporting this. We are experiencing some issues with the astro department websites atm.

However, we already decided to gradually move all datasets to github (https://github.com/astroML/astroML/issues/154), so now I upload the ones being hosted at this location.

**Comment by saint-germain** [comment]
Thanks for your answer! In the meantime I will implement a hacky solution: hosting URL-modified versions of the data fetch functions on my repo.

The reason I am doing this is because I am running some notebooks on binder for an ML course and I'd rather have an full AstroML installation from source.

**Comment by bsipocz** [comment]
PR to move those files to github is in the work, so if you wait until tomorrow there won't be any need for hacking it yourself :)

**Comment by saint-germain** [comment]
Good to know! The course will start next Monday, so no worries there :)

**Comment by bsipocz** [comment]
If you're using any of the source codes to reproduce the figures from the book, please use the version from the repo (https://github.com/astroML/astroML_figures) rather than the webpage. The latter hasn't yet been updated.
