### ISSUE TITLE
Book: GMM is not available in current sklearn library

### ISSUE THREAD

**Issue by jramirezpr** [astroML/astroML#183]
from the book example: 
http://www.astroml.org/book_figures/chapter4/fig_GMM_1D.html
GMM is being imported, but this is not part of the modern sklearn library.  Refactoring this example would ease reproducibility.

**Comment by bsipocz** [comment]
The webpage has not yet been updated, so for now I would suggest to use the figure source codes directly from the repository: https://github.com/astroML/astroML_figures


For fig 4.2: https://github.com/astroML/astroML_figures/blob/master/book_figures/chapter4/fig_GMM_1D.py

**Comment by jramirezpr** [comment]
Thank you for the reference.
