### ISSUE TITLE
Add project website

### ISSUE THREAD

**Issue by zdroid** [astroML/astroML#209]
https://www.astroml.org/ should be put as the website in this repository's description.

**Comment by bsipocz** [comment]
The link to the website is right in the middle of the Readme in this repo. 

Have you had something else in mind?

**Comment by zdroid** [comment]
Many people don't read Readme (:laughing:). I meant adding website like this (screenshot is from my repository):
![Screenshot from 2020-03-07 12-35-02](https://user-images.githubusercontent.com/2725611/76142670-15689300-6070-11ea-8d3a-86f0863443ec.png)

**Comment by bsipocz** [comment]
Oh, we can certainly have that, thanks for pointing out. As for people not reading the readme, well, 🤷‍♀
