### ISSUE TITLE
https://www.astroml.org/ doesn't work properly

### ISSUE THREAD

**Issue by zdroid** [astroML/astroML#215]
This is what appears on it:
![Screenshot from 2020-04-18 00-49-32](https://user-images.githubusercontent.com/2725611/79619892-7b841380-810e-11ea-9675-ae825a5d4cfa.png)

Was site deleted by accident? :/

**Comment by bsipocz** [comment]
we had some DNS issues yesterday, and the fix took some time to propagate. 

The site should be now back online.
