### ISSUE TITLE
Where is the source code for the two-point correlation figure? 

### ISSUE THREAD

**Issue by ljmartin** [astroML/astroML#217]
Hi AstroML,
I'd like to calculate the two point correlation for some binary-featurized data (nothing to do with astro) so I borrowed the source code from the astroML `two_point` function (swapping to BallTree to use `metric=jaccard` first). I got funny results so would like to start from a working example. A docs page ( https://www.astroml.org/user_guide/correlation_functions.html  ) mentions to follow the source code for the figure, but I can't find it. Can someone please point me to the code for that figure? 
Thanks!

**Comment by bsipocz** [comment]
@ljmartin - It's the same as figure 6.17 in the textbook, please find the source code at this link: https://www.astroml.org/book_figures/chapter6/fig_correlation_function.html
