### ISSUE TITLE
The file "examples/datasets/truncate_nsa_data.py" does not appear to exist either at this repo or the nsatlaas.org website.

### ISSUE THREAD

**Issue by ismaelharunid** [astroML/astroML#236]
In many of the nsa python files there is a comment that references a non-existent file.  Example:

```python
The NASA Sloan Atlas dataset is contained in a ~0.5GB available at
http://www.nsatlas.org/data
This function fetches a ~50MB subset of that data.  This subset is created
using the code that can be found at examples/datasets/truncate_nsa_data.py
```

The file "`examples/datasets/truncate_nsa_data.py" does not appear to exist either at this repo or the nsatlaas.org website.`

Can we get this corrected to show the correct script and location?

**Comment by bsipocz** [comment]
I'll clean up the comments in the file as we don't host and maintain the truncate script in this repo, but host the truncated data file. 

Is there any particular reason you are interested in the script? The original one from over 8 years ago can be seen here:
 https://github.com/astroML/astroML/blob/98453a727b7b6f10bc3dedb707293ce39aea552c/examples/datasets/truncate_nsa_data.py

**Comment by ismaelharunid** [comment]
Not really a particular reason other then I thought it would be more friendly if that comment was accurate.  Like myself others might be trying to understand how to use the module, so it helps when urls, citations, etc... are meaningful.  great work and thank you.
