### ISSUE TITLE
Upload to pypi?

### ISSUE THREAD

**Issue by olebole** [astroML/astroML#249]
I just noticed that there is a version 1.0 since a year, which was undiscovered since I watch on PyPI here.
Maybe the 1.0 version could be uploaded there?
Thanks!

**Comment by bsipocz** [comment]
A new bugfix one needs to be done first, I'll try to get back to it very soon.

**Comment by bsipocz** [comment]
1.0.2 is out on pypi. I'm closing this issue now, but please let me know if you run into any issues with it.

**Comment by olebole** [comment]
Thank you! I uploaded 1.0.2, and all tests on our CI platforms pass.
