### ISSUE TITLE
Interactive examples for astroML

### ISSUE THREAD

**Issue by edublancas** [astroML/astroML#272]
Hi astroML team!

My team maintains a few [open-source](https://github.com/ploomber/jupysql) projects, and we've seen that having interactive examples greatly helps newcomers! We're maintaining a binder cluster that provides ephemeral JupyterLab sessions ([example](https://binder.ploomber.io/v2/gh/ploomber/jupysql/master?urlpath=lab/tree/doc/quick-start.md)). It essentially spins up a JupyterLab session with pre-made examples.

We're happy to sponsor GeneticAlgorithmPython with some compute power. If you're interested, please get in touch with me! (my contact info is in my [profile](https://github.com/edublancas/))

**Comment by bsipocz** [comment]
Hi @edublancas 👋 

Thank you for the offer. As of now we're not looking for extra compute power for our interactive examples. 

Links to binder and colab are already rendered in them, and we haven't received feedback that our users find this insufficient.

**Comment by edublancas** [comment]
sure! If anything changes, feel free to reach out!
