### ISSUE TITLE
SDSS filters not available

### ISSUE THREAD

**Issue by DanielAndreasen** [astroML/astroML#51]
Hi,

Thanks for a wonderful work and an amazing package.

I tried to run one of the pictures from the homepage

    from astroML.datasets import fetch_sdss_filter
    u = fetch_sdss_filter('u')

But I get an error. Basically it is because the URL parsed no longer exist:
http://www.sdss.org/dr7/instruments/imager/filters/u.dat

I do not know where the data is, so I don't have an solution.

**Comment by jbochanski** [comment]
Hi Daniel,
It looks like it has been migrated to
http://classic.sdss.org/dr7/instruments/imager/filters/u.dat

Cheers,
John

**Comment by DanielAndreasen** [comment]
Indeed it looks like it. I'll make a pull request and correct the link. Thanks for the help.

**Comment by jakevdp** [comment]
Thanks for reporting the issue! (and providing the fix :smile:)

**Comment by DanielAndreasen** [comment]
You are welcome (for reporting the issue).

Cheers,
Daniel
