### ISSUE TITLE
Using hist forces plot to appear

### ISSUE THREAD

**Issue by Gabriel-p** [astroML/astroML#54]
I'm currently using the `hist` function (`from astroML.plotting import hist`) to obtain bin edges, not to generate a plot.

When a `plt.show()` line appears _much_ further down the code, the histogram generated by `hist` is shown next to whatever I am plotting.

Can this behaviour be prevented somehow?

**Comment by jakevdp** [comment]
Yes, the ``hist()`` function is meant as a plotting function. If you want to compute the histogram without generating a plot, you can use the binning functions directly, e.g.
```
from astroML.density_estimation import bayesian_blocks
x = np.random.random(100)
bins = bayesian_blocks(x)
```
If you take a look at the [source code for ``hist()``](https://github.com/astroML/astroML/blob/master/astroML/plotting/hist_tools.py#L10) you'll see that it's just a thin wrapper around the sequence of computing bins plus plotting.

**Comment by Gabriel-p** [comment]
Thanks for the reply Jake.

I currently use the `hist()` function since I let the user choose which binning method to use (ie: bayesian blocks, scott, freedman or knuth). The solution you wrote above would work when the method chosen is Bayesian blocks, but how could I use a more general approach like the one `hist()` allows?

**Comment by jakevdp** [comment]
That would be another convenience function, which is not in astroML. Real quick (and untested) you could use something like this:

``` python
import numpy as np

from astroML.density_estimation import\
    scotts_bin_width, freedman_bin_width,\
    knuth_bin_width, bayesian_blocks


def histogram(x, bins=10, range=None, *args, **kwargs):
    if isinstance(bins, str) and "weights" in kwargs:
        warnings.warn("weights argument is not supported: it will be ignored.")
        kwargs.pop('weights')

    x = np.asarray(x)

    # if range is specified, we need to truncate the data for
    # the bin-finding routines
    if (range is not None and (bins in ['blocks',
                                        'knuth', 'knuths',
                                        'scott', 'scotts',
                                        'freedman', 'freedmans'])):
        x = x[(x >= range[0]) & (x <= range[1])]

    if bins in ['blocks']:
        bins = bayesian_blocks(x)
    elif bins in ['knuth', 'knuths']:
        dx, bins = knuth_bin_width(x, True, disp=False)
    elif bins in ['scott', 'scotts']:
        dx, bins = scotts_bin_width(x, True)
    elif bins in ['freedman', 'freedmans']:
        dx, bins = freedman_bin_width(x, True)
    elif isinstance(bins, str):
        raise ValueError("unrecognized bin code: '%s'" % bins)

    return np.histogram(x, bins, range, **kwargs)
```

In fact, this might be worth adding as a utility in ``astroML``. What do you think?

**Comment by Gabriel-p** [comment]
Wonderful @jakevdp, thank you very much for taking the time to put this function together. If you want I can test it and come back to you, but I'm traveling out of city in a few hours and will be able to pay more attention to this mid next week.

**Comment by Gabriel-p** [comment]
Month and a half later, here I am. Sorry for the **laaate** response Jake.

I tested the code you pasted above and I got good results with all the methods, except `knuth`. This method will often times crash with the error:

````
Traceback (most recent call last):
  File "/home/gabriel/Descargas/del.py", line 48, in <module>
    bin_edges.append(histogram(x, bin_mode)[1])
  File "/home/gabriel/Descargas/del.py", line 28, in histogram
    dx, bins = knuth_bin_width(x, True)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 226, in knuth_bin_width
    M = optimize.fmin(knuthF, len(bins0))[0]
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 351, in fmin
    res = _minimize_neldermead(func, x0, args, callback=callback, **opts)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 443, in _minimize_neldermead
    fxr = func(xr)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 261, in function_wrapper
    return function(x, *args)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 155, in __call__
    return self.eval(M)
  File "/usr/local/lib/python2.7/dist-packages/astroML/density_estimation/histtools.py", line 173, in eval
    nk, bins = np.histogram(self.data, bins)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 211, in histogram
    sa.searchsorted(bins[-1], 'right')]
IndexError: index -1 is out of bounds for axis 0 with size 0
````

Other times it will work just fine. This is the code I used to call the function you pasted:

````
import matplotlib.pyplot as plt

x = np.random.random(1000)
y = np.random.random(1000)

# bin_mode = 'blocks'
# bin_mode = 'scott'
# bin_mode = 'freedman'
bin_mode = 'knuth'

bin_edges = []
for dim in [x, y]:
    bin_edges.append(histogram(x, bin_mode)[1])

fig, ax = plt.subplots()
plt.scatter(x, y)
ax.set_xticks(bin_edges[0], minor=False)
ax.set_yticks(bin_edges[1], minor=False)
ax.xaxis.grid(True, which='major')
ax.yaxis.grid(True, which='major')
plt.show()
 ````

**Comment by bsipocz** [comment]
This issue seems to be solved. Feel free to reopen if there is still some action items concerning the astroML package.
