### ISSUE TITLE
Fetch routine crash with new astropy version

### ISSUE THREAD

**Issue by kdhiner** [astroML/astroML#55]
I updated to astropy v1.0 today and found that now the fetch routines in astroML crash.

OError                                   Traceback (most recent call last)
<ipython-input-1-48ccb025719e> in <module>()
     40 #------------------------------------------------------------
     41 # Fetch the great wall data
---> 42 X = fetch_great_wall()
     43 
     44 #------------------------------------------------------------

IOError: [Errno 13] Permission denied: '/Users/Kyle/.astropy/config/astropy.1.0.cfg'

**Comment by kdhiner** [comment]
I managed to solve this on my own. I am not sure what the problem actually was, but uninstalling astropy and reinstalling astropy cleared the error.

**Comment by jakevdp** [comment]
Very strange... the only part of ``astropy`` that should be used there is ``astropy.io.fits``.
My guess is it was some sort of permissions thing – perhaps your original astropy installation was on root, or something like that.

I'm going to close the issue, as it looks like it doesn't have to do with ``astroML``. Thanks for reporting!
