### ISSUE TITLE
Bug in cas_query? 

### ISSUE THREAD

**Issue by kareemelbadry** [astroML/astroML#59]
When trying to run tools.query_plate_mjd_fiber(), I kept getting the error 

ValueError: #Table1
plate,mjd,fiberid
2128,53800,575
2128,53800,577
2128,53800,578
2128,53800,579
2128,53800,581

I dug around in the code, and the error comes from line 78 of cas_query.py. The "output" array is 

output = ['#Table1\n', 'plate,mjd,fiberid\n', '2128,53800,575\n', '2128,53800,577\n', '2128,53800,578\n', '2128,53800,579\n', '2128,53800,581\n'],

so the map() in line 78 is calling int('plate'), int('mjd'), etc, which raises an error. 

I got around this by changing line 76 to
for i, line in enumerate(output[2:]):

But I think the problem is that for some reason, the comment '#Table1\n' is getting added to output by sql_query().

**Comment by jakevdp** [comment]
Hi – thanks for the report. It looks like the string returned by the CAS server has changed since the initial release of the code. It looks like your fix is the correct one; would you like to submit a pull request?

**Comment by bsipocz** [comment]
This got fixed in 13b35ffafc11cef8bd4d9bf6c911c1183ce80b8c
