### ISSUE TITLE
fig 9.12; fig_rrlyrae_treevis.py and sklearn.tree.DecisionTreeClassifier

### ISSUE THREAD

**Issue by richardgmcmahon** [astroML/astroML#78]
I am using:

sklearn.**version**:  0.16.1
astroML.**version**:  0.3

 File "fig_rrlyrae_treevis.py", line 242, in <module>
    random_state=0, criterion='entropy')
TypeError: **init**() got an unexpected keyword argument 'compute_importances'

I added these lines to fix my fork:

```
# in 0.14+ Setting compute_importances=True is no longer required. 
try:
  # version < 0.14
 clf = DecisionTreeClassifier(compute_importances=True,
                             random_state=0, criterion='entropy')
except:
  # version 0.14+
  clf = DecisionTreeClassifier(
                             random_state=0, criterion='entropy')
```

see also: https://github.com/astroML/astroML/pull/77

**Comment by jakevdp** [comment]
Thanks – there have been a number of changes to the scikit-learn API in the last year or so. I plan to update those in the next release.

**Comment by bsipocz** [comment]
Issue has been moved to the other repo.
