### ISSUE TITLE
New release with updated data urls

### ISSUE THREAD

**Issue by aragilar** [astroML/astroML#88]
It appears some of the data files have moved, and the current master has the new locations (e.g. sdss_corrected_spectra module). Could a new release be made with the updated urls, as the error message when numpy tries to read the 404 produced doesn't make it obvious what the problem is.

**Comment by jakevdp** [comment]
Yes... I promised @ivezic last week that I'd do that soon... just too much on my plate. I'll try to get to it.

**Comment by corbett** [comment]
If anyone could share with me what the updated data URLS are as of July 2017?
Trying to download SDSS data and the following doesn't exist (or anything down the chain)
http://www.astro.washington.edu/users/ivezic/DMbook/data/SDSSspecgalsDR8.fit
Christine

**Comment by corbett** [comment]
Don't need all of them, just one and I'm good from there. Teaching a class hopefully with this module as an example and it'd be great for students to easily download a few examples.

**Comment by ivezic** [comment]
Hi Christine,

we are very sorry about this. The problem comes from the fact that our departmental
web server just died. Jake, do we have those files somewhere on github?

For now, I copied the file that gave you problems and a few other frequently used files
to my dropbox folder:
https://www.dropbox.com/sh/l01yg08wj6cmfj4/AAA-EsRDPw4qaJE3t8UWvUfZa?dl=0 <https://www.dropbox.com/sh/l01yg08wj6cmfj4/AAA-EsRDPw4qaJE3t8UWvUfZa?dl=0>

Please let me know if this works for you.

       Cheers, Zeljko

**Comment by corbett** [comment]
Hey,

Thank you! Yes I already recreated the one file by entering the query to
the CASJobs on SDSS and it was good practice! Thank you for a link to the
other data, it will be good for the final student projects to have access
to and the process of recreating the one data file did take some time.

Christine

Sent from the future

🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
Dr. Christine Corbett Moran
www.christinecorbettmoran.com

**Comment by corbett** [comment]
@ivezic One more thing, I've been able to regenerate data on SDSS if the SQL query is provided or if you linked it to me in the dropbox (THANK YOU), but I'd like to have one problem with the following data:
DATA_URL = ('http://www.astro.washington.edu/users/ivezic/'
            'sdss/catalogs/stripe82calibStars_v2.6.dat.gz')
DATA_URL_2MASS = ('http://www.astro.washington.edu/users/ivezic/'
                  'sdss/catalogs/stripe82calibStars_2MASS_v2.6.dat.gz')

Do you have that anywhere? The department webserver is still down :(

**Comment by ivezic** [comment]
Hi Christine,
these files should be available now. Please let me know if you still cannot access them.
     Cheers, Zeljko

**Comment by corbett** [comment]
Yep, just saw that they are! Thank you! I updated our assignment to reflect
that and cached the data on my astroML_data dropbox just in case.
BTW our assignments using the code are here:
https://github.com/SummerAppSpace/Chapter4/blob/master/CAPSTONE.md
https://github.com/SummerAppSpace/Chapter4/blob/master/README.md
https://github.com/SummerAppSpace/ClassifyGalaxies/blob/master/README.md


Sent from the future

🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
Dr. Christine Corbett Moran
www.christinecorbettmoran.com

**Comment by bsipocz** [comment]
All data URLs now work with v0.4rc1 and in the near future we'll make it even more future proof by moving all data file downloads from https://github.com/astroML/astroML-data/ (https://github.com/astroML/astroML/issues/154)
