### ISSUE TITLE
Issues with Bayesian Blocks and histtype='step'

### ISSUE THREAD

**Issue by rprechelt** [astroML/astroML#92]
I'm having a bizarre issue with Bayesian blocks; the code below, which I lifted straight from the examples and made some small modifications, gives me unexpected results

```
from astroML.plotting import hist
ax_r = plt.subplot(gs[1, 0])

# plot regular matplotlib histogram
ax_r.hist(r, bins=25, alpha=0.35, normed=True, fc=col)
```

gives the expected matplotlib 

![regular](https://cloud.githubusercontent.com/assets/10441161/21958960/31e6fb22-da7f-11e6-9b0e-0ca4784c1ba1.png)

All's good. However, trying to overlay a Bayesian blocks histogram on top, 

```
from astroML.plotting import hist
ax_r = plt.subplot(gs[1, 0])

# plot regular matplotlib histogram
ax_r.hist(r, bins=25, alpha=0.35, normed=True, fc=col)

hist(r, 'blocks', histtype='step',  normed=True, lw=2, fc=(0, 0, 0, 0.0), edgecolor=col)
```
results in the correct overlay, but a strange spike at the start of the plot. This may be a side effect of the algorithm, however, it gets weirder. 
![step](https://cloud.githubusercontent.com/assets/10441161/21958967/67be124e-da7f-11e6-9320-5226c5ffab9b.png)

If I then delete the astroML `histtype='step'`, I lose the first histogram, and the spike is the only visible feature

```
from astroML.plotting import hist
ax_r = plt.subplot(gs[1, 0])

# plot regular matplotlib histogram
ax_r.hist(r, bins=25, alpha=0.35, normed=True, fc=col)

hist(r, 'blocks', normed=True, lw=2, fc=(0, 0, 0, 0.0), edgecolor=col)
```

![spike](https://cloud.githubusercontent.com/assets/10441161/21958954/1a033372-da7f-11e6-9fd4-3842038e1a35.png)

This behaviour seems like a bug; however, it may just be a side-effect of my usage. 

Can you shed any insight?

**Comment by bsipocz** [comment]
This functionality has been moved upstream to astropy. I keep this issue open though for a little more here and investigate a bit, and if needed will reopen it upstream.

**Comment by bsipocz** [comment]
@rprechelt - I hope you have solved the issue since. Sadly given the minimal information here I wasn't able to reproduce it.

Also, as I mentioned above the histograms have been moved to `astropy.stats` and `astropy.visualization.hist`. If you still experiencing this problem, please open an issue at https://github.com/astropy/astropy with a preferably full, copy paste-able example. Feel free to ping me there and I'll have a look at it.
