### ISSUE TITLE
Minor error in webpage title

### ISSUE THREAD

**Issue by jakevdp** [astroML/astroML#96]
http://www.astroml.org/book_figures/chapter1/fig_moving_objects_multicolor.html

"SDSS Stripe 82 Moving Object Catalog” should be "SDSS Moving Object Catalog” (it’s not just Stripe 82).

**Comment by bsipocz** [comment]
This has been addressed in https://github.com/astroML/astroML/pull/113 and https://github.com/astroML/astroml.github.com/pull/2
